apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service
  namespace: stratifyr
  labels:
    app: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - name: security-service
          image: asia-south1-docker.pkg.dev/stratifyr/stratifyr/security-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: security-svc-secret
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
  namespace: stratifyr
spec:
  selector:
    app: security-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP