apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service
  namespace: stratifyr-stage
  labels:
    app: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - name: security-service
          image: asia-south1-docker.pkg.dev/stratifyr/stratifyr/security-service:dev-git-sha # will be replaced in CI/CD
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 9000
          envFrom:
            - secretRef:
                name: security-svc-secret
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
  namespace: stratifyr-stage
spec:
  selector:
    app: security-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: grpc
      port: 9000
      targetPort: 9000
  type: ClusterIP