apiVersion: batch/v1
kind: Job
metadata:
  name: data-loader
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      restartPolicy: Never
      containers:
        - name: data-loader
          image: stratifyr/data-loader:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: data-loader-secrets
          command:
            - sh
            - -c
            - |
              ./data-loader load securities &&
              ./data-loader load metrics &&
              ./data-loader load market-holidays &&
              ./data-loader load ltp &&
              ./data-loader load security-stats --start-date=2024-06-07 --end-date=2025-06-07 &&
              ./data-loader load security-metrics --start-date=2025-06-07 --end-date=2025-06-07