// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.1
// source: security-service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecurityServiceClient is the client API for SecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecurityServiceClient interface {
	GetMarketDays(ctx context.Context, in *GetMarketDaysRequest, opts ...grpc.CallOption) (*GetMarketDaysResponse, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	GetSecurities(ctx context.Context, in *GetSecuritiesRequest, opts ...grpc.CallOption) (*GetSecuritiesResponse, error)
	GetMarketDataJobs(ctx context.Context, in *GetMarketDataJobsRequest, opts ...grpc.CallOption) (*GetMarketDataJobsResponse, error)
	UpdateMarketDataJob(ctx context.Context, in *UpdateMarketDataJobRequest, opts ...grpc.CallOption) (*UpdateMarketDataJobResponse, error)
}

type securityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityServiceClient(cc grpc.ClientConnInterface) SecurityServiceClient {
	return &securityServiceClient{cc}
}

func (c *securityServiceClient) GetMarketDays(ctx context.Context, in *GetMarketDaysRequest, opts ...grpc.CallOption) (*GetMarketDaysResponse, error) {
	out := new(GetMarketDaysResponse)
	err := c.cc.Invoke(ctx, "/security.SecurityService/GetMarketDays", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, "/security.SecurityService/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) GetSecurities(ctx context.Context, in *GetSecuritiesRequest, opts ...grpc.CallOption) (*GetSecuritiesResponse, error) {
	out := new(GetSecuritiesResponse)
	err := c.cc.Invoke(ctx, "/security.SecurityService/GetSecurities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) GetMarketDataJobs(ctx context.Context, in *GetMarketDataJobsRequest, opts ...grpc.CallOption) (*GetMarketDataJobsResponse, error) {
	out := new(GetMarketDataJobsResponse)
	err := c.cc.Invoke(ctx, "/security.SecurityService/GetMarketDataJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) UpdateMarketDataJob(ctx context.Context, in *UpdateMarketDataJobRequest, opts ...grpc.CallOption) (*UpdateMarketDataJobResponse, error) {
	out := new(UpdateMarketDataJobResponse)
	err := c.cc.Invoke(ctx, "/security.SecurityService/UpdateMarketDataJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityServiceServer is the server API for SecurityService service.
// All implementations must embed UnimplementedSecurityServiceServer
// for forward compatibility
type SecurityServiceServer interface {
	GetMarketDays(context.Context, *GetMarketDaysRequest) (*GetMarketDaysResponse, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	GetSecurities(context.Context, *GetSecuritiesRequest) (*GetSecuritiesResponse, error)
	GetMarketDataJobs(context.Context, *GetMarketDataJobsRequest) (*GetMarketDataJobsResponse, error)
	UpdateMarketDataJob(context.Context, *UpdateMarketDataJobRequest) (*UpdateMarketDataJobResponse, error)
	mustEmbedUnimplementedSecurityServiceServer()
}

// UnimplementedSecurityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSecurityServiceServer struct {
}

func (UnimplementedSecurityServiceServer) GetMarketDays(context.Context, *GetMarketDaysRequest) (*GetMarketDaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketDays not implemented")
}
func (UnimplementedSecurityServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedSecurityServiceServer) GetSecurities(context.Context, *GetSecuritiesRequest) (*GetSecuritiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecurities not implemented")
}
func (UnimplementedSecurityServiceServer) GetMarketDataJobs(context.Context, *GetMarketDataJobsRequest) (*GetMarketDataJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketDataJobs not implemented")
}
func (UnimplementedSecurityServiceServer) UpdateMarketDataJob(context.Context, *UpdateMarketDataJobRequest) (*UpdateMarketDataJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMarketDataJob not implemented")
}
func (UnimplementedSecurityServiceServer) mustEmbedUnimplementedSecurityServiceServer() {}

// UnsafeSecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityServiceServer will
// result in compilation errors.
type UnsafeSecurityServiceServer interface {
	mustEmbedUnimplementedSecurityServiceServer()
}

func RegisterSecurityServiceServer(s grpc.ServiceRegistrar, srv SecurityServiceServer) {
	s.RegisterService(&SecurityService_ServiceDesc, srv)
}

func _SecurityService_GetMarketDays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketDaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).GetMarketDays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/security.SecurityService/GetMarketDays",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).GetMarketDays(ctx, req.(*GetMarketDaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/security.SecurityService/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_GetSecurities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecuritiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).GetSecurities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/security.SecurityService/GetSecurities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).GetSecurities(ctx, req.(*GetSecuritiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_GetMarketDataJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketDataJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).GetMarketDataJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/security.SecurityService/GetMarketDataJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).GetMarketDataJobs(ctx, req.(*GetMarketDataJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_UpdateMarketDataJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMarketDataJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).UpdateMarketDataJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/security.SecurityService/UpdateMarketDataJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).UpdateMarketDataJob(ctx, req.(*UpdateMarketDataJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityService_ServiceDesc is the grpc.ServiceDesc for SecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "security.SecurityService",
	HandlerType: (*SecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketDays",
			Handler:    _SecurityService_GetMarketDays_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _SecurityService_GetMetrics_Handler,
		},
		{
			MethodName: "GetSecurities",
			Handler:    _SecurityService_GetSecurities_Handler,
		},
		{
			MethodName: "GetMarketDataJobs",
			Handler:    _SecurityService_GetMarketDataJobs_Handler,
		},
		{
			MethodName: "UpdateMarketDataJob",
			Handler:    _SecurityService_UpdateMarketDataJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "security-service.proto",
}
