// Code generated by gofr.dev/cli/gofr. DO NOT EDIT.
// versions:
// 	gofr-cli v0.7.0
// 	gofr.dev v1.39.0
// 	source: security.proto


package grpc

import (
	"context"
	"fmt"
	"reflect"
)

// Request Wrappers
type SecurityIndexRequestWrapper struct {
	ctx context.Context
	*SecurityIndexRequest
}

func (h *SecurityIndexRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *SecurityIndexRequestWrapper) Param(s string) string {
	return ""
}

func (h *SecurityIndexRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *SecurityIndexRequestWrapper) Bind(p interface{}) error {
	ptr := reflect.ValueOf(p)
	if ptr.Kind() != reflect.Ptr {
		return fmt.Errorf("expected a pointer, got %T", p)
	}

	hValue := reflect.ValueOf(h.SecurityIndexRequest).Elem()
	ptrValue := ptr.Elem()

	for i := 0; i < hValue.NumField(); i++ {
		field := hValue.Type().Field(i)
		if field.Name == "state" || field.Name == "sizeCache" || field.Name == "unknownFields" {
			continue
		}

		if field.IsExported() {
			ptrValue.Field(i).Set(hValue.Field(i))
		}
	}

	return nil
}

func (h *SecurityIndexRequestWrapper) HostName() string {
	return ""
}

func (h *SecurityIndexRequestWrapper) Params(s string) []string {
	return nil
}