name: Build and Deploy

on:
  push:
    branches: [ development ]

jobs:
  build-deploy:
    name: CI/CD ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: security-service
            type: deployment
            dockerfile: ./Dockerfile
            docker_context: .
            port: 8002
          - name: market-data-loader
            type: deployment
            dockerfile: ./daemon/market-data-loader/Dockerfile
            docker_context: ./daemon/market-data-loader
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      - name: Build and Push Docker image
        run: |
          IMAGE=ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ matrix.name }}:${{ github.sha }}
          docker build -t $IMAGE -f ${{ matrix.dockerfile }} ${{ matrix.docker_context }}
          docker push $IMAGE
