// Code generated by gofr.dev/cli/gofr. DO NOT EDIT.
// versions:
// 	gofr-cli v0.7.0
// 	gofr.dev v1.39.0
// 	source: security-service.proto


package grpc

import (
	"context"
	"fmt"
	"reflect"

	"github.com/stratifyr/security-service/proto"
)

// Request Wrappers
type GetMetricsRequestWrapper struct {
	ctx context.Context
	*proto.GetMetricsRequest
}

func (h *GetMetricsRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *GetMetricsRequestWrapper) Param(s string) string {
	return ""
}

func (h *GetMetricsRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *GetMetricsRequestWrapper) Bind(p interface{}) error {
	ptr := reflect.ValueOf(p)
	if ptr.Kind() != reflect.Ptr {
		return fmt.Errorf("expected a pointer, got %T", p)
	}

	hValue := reflect.ValueOf(h.GetMetricsRequest).Elem()
	ptrValue := ptr.Elem()

	for i := 0; i < hValue.NumField(); i++ {
		field := hValue.Type().Field(i)
		if field.Name == "state" || field.Name == "sizeCache" || field.Name == "unknownFields" {
			continue
		}

		if field.IsExported() {
			ptrValue.Field(i).Set(hValue.Field(i))
		}
	}

	return nil
}

func (h *GetMetricsRequestWrapper) HostName() string {
	return ""
}

func (h *GetMetricsRequestWrapper) Params(s string) []string {
	return nil
}
type GetSecuritiesRequestWrapper struct {
	ctx context.Context
	*proto.GetSecuritiesRequest
}

func (h *GetSecuritiesRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *GetSecuritiesRequestWrapper) Param(s string) string {
	return ""
}

func (h *GetSecuritiesRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *GetSecuritiesRequestWrapper) Bind(p interface{}) error {
	ptr := reflect.ValueOf(p)
	if ptr.Kind() != reflect.Ptr {
		return fmt.Errorf("expected a pointer, got %T", p)
	}

	hValue := reflect.ValueOf(h.GetSecuritiesRequest).Elem()
	ptrValue := ptr.Elem()

	for i := 0; i < hValue.NumField(); i++ {
		field := hValue.Type().Field(i)
		if field.Name == "state" || field.Name == "sizeCache" || field.Name == "unknownFields" {
			continue
		}

		if field.IsExported() {
			ptrValue.Field(i).Set(hValue.Field(i))
		}
	}

	return nil
}

func (h *GetSecuritiesRequestWrapper) HostName() string {
	return ""
}

func (h *GetSecuritiesRequestWrapper) Params(s string) []string {
	return nil
}
type GetMarketDaysRequestWrapper struct {
	ctx context.Context
	*proto.GetMarketDaysRequest
}

func (h *GetMarketDaysRequestWrapper) Context() context.Context {
	return h.ctx
}

func (h *GetMarketDaysRequestWrapper) Param(s string) string {
	return ""
}

func (h *GetMarketDaysRequestWrapper) PathParam(s string) string {
	return ""
}

func (h *GetMarketDaysRequestWrapper) Bind(p interface{}) error {
	ptr := reflect.ValueOf(p)
	if ptr.Kind() != reflect.Ptr {
		return fmt.Errorf("expected a pointer, got %T", p)
	}

	hValue := reflect.ValueOf(h.GetMarketDaysRequest).Elem()
	ptrValue := ptr.Elem()

	for i := 0; i < hValue.NumField(); i++ {
		field := hValue.Type().Field(i)
		if field.Name == "state" || field.Name == "sizeCache" || field.Name == "unknownFields" {
			continue
		}

		if field.IsExported() {
			ptrValue.Field(i).Set(hValue.Field(i))
		}
	}

	return nil
}

func (h *GetMarketDaysRequestWrapper) HostName() string {
	return ""
}

func (h *GetMarketDaysRequestWrapper) Params(s string) []string {
	return nil
}