// Code generated by gofr.dev/cli/gofr. DO NOT EDIT.
// versions:
// 	gofr-cli v0.7.0
// 	gofr.dev v1.39.0
// 	source: security-service.proto

package grpc

import (
	"gofr.dev/pkg/gofr"
	"gofr.dev/pkg/gofr/metrics"
	"google.golang.org/grpc"

	"github.com/stratifyr/security-service/proto"
)

type SecurityServiceGoFrClient interface {
	GetMarketDays(ctx *gofr.Context, req *proto.GetMarketDaysRequest, opts ...grpc.CallOption) (*proto.GetMarketDaysResponse, error)
	GetMetrics(ctx *gofr.Context, req *proto.GetMetricsRequest, opts ...grpc.CallOption) (*proto.GetMetricsResponse, error)
	GetSecurities(ctx *gofr.Context, req *proto.GetSecuritiesRequest, opts ...grpc.CallOption) (*proto.GetSecuritiesResponse, error)
	GetMarketDataJobs(ctx *gofr.Context, req *proto.GetMarketDataJobsRequest, opts ...grpc.CallOption) (*proto.GetMarketDataJobsResponse, error)
	UpdateMarketDataJob(ctx *gofr.Context, req *proto.UpdateMarketDataJobRequest, opts ...grpc.CallOption) (*proto.UpdateMarketDataJobResponse, error)
	HealthClient
}

type SecurityServiceClientWrapper struct {
	client proto.SecurityServiceClient
	HealthClient
}

func NewSecurityServiceGoFrClient(host string, metrics metrics.Manager, dialOptions ...grpc.DialOption) (SecurityServiceGoFrClient, error) {
	conn, err := createGRPCConn(host, "SecurityService", dialOptions...)
	if err != nil {
		return &SecurityServiceClientWrapper{
			client:       nil,
			HealthClient: &HealthClientWrapper{client: nil},
		}, err
	}

	metricsOnce.Do(func() {
		metrics.NewHistogram("app_gRPC-Client_stats", "Response time of gRPC client in milliseconds.", gRPCBuckets...)
	})

	res := proto.NewSecurityServiceClient(conn)
	healthClient := NewHealthClient(conn)

	return &SecurityServiceClientWrapper{
		client: res,
		HealthClient: healthClient,
	}, nil
}


func (h *SecurityServiceClientWrapper) GetMarketDays(ctx *gofr.Context, req *proto.GetMarketDaysRequest,
	opts ...grpc.CallOption) (*proto.GetMarketDaysResponse, error) {
	result, err := invokeRPC(ctx, "/SecurityService/GetMarketDays", func() (interface{}, error) {
		return h.client.GetMarketDays(ctx.Context, req, opts...)
	}, "app_gRPC-Client_stats")

	if err != nil {
		return nil, err
	}
	return result.(*proto.GetMarketDaysResponse), nil
}
func (h *SecurityServiceClientWrapper) GetMetrics(ctx *gofr.Context, req *proto.GetMetricsRequest,
	opts ...grpc.CallOption) (*proto.GetMetricsResponse, error) {
	result, err := invokeRPC(ctx, "/SecurityService/GetMetrics", func() (interface{}, error) {
		return h.client.GetMetrics(ctx.Context, req, opts...)
	}, "app_gRPC-Client_stats")

	if err != nil {
		return nil, err
	}
	return result.(*proto.GetMetricsResponse), nil
}
func (h *SecurityServiceClientWrapper) GetSecurities(ctx *gofr.Context, req *proto.GetSecuritiesRequest,
	opts ...grpc.CallOption) (*proto.GetSecuritiesResponse, error) {
	result, err := invokeRPC(ctx, "/SecurityService/GetSecurities", func() (interface{}, error) {
		return h.client.GetSecurities(ctx.Context, req, opts...)
	}, "app_gRPC-Client_stats")

	if err != nil {
		return nil, err
	}
	return result.(*proto.GetSecuritiesResponse), nil
}
func (h *SecurityServiceClientWrapper) GetMarketDataJobs(ctx *gofr.Context, req *proto.GetMarketDataJobsRequest,
	opts ...grpc.CallOption) (*proto.GetMarketDataJobsResponse, error) {
	result, err := invokeRPC(ctx, "/SecurityService/GetMarketDataJobs", func() (interface{}, error) {
		return h.client.GetMarketDataJobs(ctx.Context, req, opts...)
	}, "app_gRPC-Client_stats")

	if err != nil {
		return nil, err
	}
	return result.(*proto.GetMarketDataJobsResponse), nil
}
func (h *SecurityServiceClientWrapper) UpdateMarketDataJob(ctx *gofr.Context, req *proto.UpdateMarketDataJobRequest,
	opts ...grpc.CallOption) (*proto.UpdateMarketDataJobResponse, error) {
	result, err := invokeRPC(ctx, "/SecurityService/UpdateMarketDataJob", func() (interface{}, error) {
		return h.client.UpdateMarketDataJob(ctx.Context, req, opts...)
	}, "app_gRPC-Client_stats")

	if err != nil {
		return nil, err
	}
	return result.(*proto.UpdateMarketDataJobResponse), nil
}

