// Code generated by gofr.dev/cli/gofr. DO NOT EDIT.
// versions:
// 	gofr-cli v0.7.0
// 	gofr.dev v1.39.0
// 	source: security-service.proto

package grpc

import (
	"context"

	"gofr.dev/pkg/gofr"
	"gofr.dev/pkg/gofr/container"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	healthpb "google.golang.org/grpc/health/grpc_health_v1"

	"github.com/stratifyr/security-service/proto"
)

// NewSecurityServiceGoFrServer creates a new instance of SecurityServiceGoFrServer
func NewSecurityServiceGoFrServer() *SecurityServiceGoFrServer {
	return &SecurityServiceGoFrServer{
		health: getOrCreateHealthServer(), // Initialize the health server
	}
}

// SecurityServiceServerWithGofr is the interface for the server implementation
type SecurityServiceServerWithGofr interface {
	GetMarketDays(*gofr.Context) (any, error)
	GetMetrics(*gofr.Context) (any, error)
	GetSecurities(*gofr.Context) (any, error)
	UpdateSecurity(*gofr.Context) (any, error)
	CreateOrUpdateSecurityStat(*gofr.Context) (any, error)
	GetMarketDataJobs(*gofr.Context) (any, error)
	UpdateMarketDataJob(*gofr.Context) (any, error)
}

// SecurityServiceServerWrapper wraps the server and handles request and response logic
type SecurityServiceServerWrapper struct {
	proto.SecurityServiceServer
	*healthServer
	Container *container.Container
	server    SecurityServiceServerWithGofr
}




// Unary method handler for GetMarketDays
func (h *SecurityServiceServerWrapper) GetMarketDays(ctx context.Context, req *proto.GetMarketDaysRequest) (*proto.GetMarketDaysResponse, error) {
	gctx := h.getGofrContext(ctx, &GetMarketDaysRequestWrapper{ctx: ctx, GetMarketDaysRequest: req})
	
	res, err := h.server.GetMarketDays(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*proto.GetMarketDaysResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}
	
	return resp, nil
}
// Unary method handler for GetMetrics
func (h *SecurityServiceServerWrapper) GetMetrics(ctx context.Context, req *proto.GetMetricsRequest) (*proto.GetMetricsResponse, error) {
	gctx := h.getGofrContext(ctx, &GetMetricsRequestWrapper{ctx: ctx, GetMetricsRequest: req})
	
	res, err := h.server.GetMetrics(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*proto.GetMetricsResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}
	
	return resp, nil
}
// Unary method handler for GetSecurities
func (h *SecurityServiceServerWrapper) GetSecurities(ctx context.Context, req *proto.GetSecuritiesRequest) (*proto.GetSecuritiesResponse, error) {
	gctx := h.getGofrContext(ctx, &GetSecuritiesRequestWrapper{ctx: ctx, GetSecuritiesRequest: req})
	
	res, err := h.server.GetSecurities(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*proto.GetSecuritiesResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}
	
	return resp, nil
}
// Unary method handler for UpdateSecurity
func (h *SecurityServiceServerWrapper) UpdateSecurity(ctx context.Context, req *proto.UpdateSecurityRequest) (*proto.UpdateSecurityResponse, error) {
	gctx := h.getGofrContext(ctx, &UpdateSecurityRequestWrapper{ctx: ctx, UpdateSecurityRequest: req})

	res, err := h.server.UpdateSecurity(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*proto.UpdateSecurityResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}

	return resp, nil
}
// Unary method handler for CreateOrUpdateSecurityStat
func (h *SecurityServiceServerWrapper) CreateOrUpdateSecurityStat(ctx context.Context, req *proto.CreateOrUpdateSecurityStatRequest) (*proto.CreateOrUpdateSecurityStatResponse, error) {
	gctx := h.getGofrContext(ctx, &CreateOrUpdateSecurityStatRequestWrapper{ctx: ctx, CreateOrUpdateSecurityStatRequest: req})

	res, err := h.server.CreateOrUpdateSecurityStat(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*proto.CreateOrUpdateSecurityStatResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}

	return resp, nil
}
// Unary method handler for GetMarketDataJobs
func (h *SecurityServiceServerWrapper) GetMarketDataJobs(ctx context.Context, req *proto.GetMarketDataJobsRequest) (*proto.GetMarketDataJobsResponse, error) {
	gctx := h.getGofrContext(ctx, &GetMarketDataJobsRequestWrapper{ctx: ctx, GetMarketDataJobsRequest: req})

	res, err := h.server.GetMarketDataJobs(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*proto.GetMarketDataJobsResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}

	return resp, nil
}
// Unary method handler for UpdateMarketDataJob
func (h *SecurityServiceServerWrapper) UpdateMarketDataJob(ctx context.Context, req *proto.UpdateMarketDataJobRequest) (*proto.UpdateMarketDataJobResponse, error) {
	gctx := h.getGofrContext(ctx, &UpdateMarketDataJobRequestWrapper{ctx: ctx, UpdateMarketDataJobRequest: req})

	res, err := h.server.UpdateMarketDataJob(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*proto.UpdateMarketDataJobResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}

	return resp, nil
}

// mustEmbedUnimplementedSecurityServiceServer ensures implementation
func (h *SecurityServiceServerWrapper) mustEmbedUnimplementedSecurityServiceServer() {}

// RegisterSecurityServiceServerWithGofr registers the server
func RegisterSecurityServiceServerWithGofr(app *gofr.App, srv SecurityServiceServerWithGofr) {
	registerServerWithGofr(app, srv, func(s grpc.ServiceRegistrar, srv any) {
		wrapper := &SecurityServiceServerWrapper{
			server:       srv.(SecurityServiceServerWithGofr),
			healthServer: getOrCreateHealthServer(),
		}

		proto.RegisterSecurityServiceServer(s, wrapper)

		wrapper.Server.SetServingStatus("Hello", healthpb.HealthCheckResponse_SERVING)
	})
}

// getGofrContext creates GoFr context
func (h *SecurityServiceServerWrapper) getGofrContext(ctx context.Context, req gofr.Request) *gofr.Context {
	return &gofr.Context{
		Context:   ctx,
		Container: h.Container,
		Request:   req,
	}
}
